export const keysData = [
  // Minor Keys
  { key: "Eb", is_major: false },
  { key: "E", is_major: false },
  { key: "F", is_major: false },
  { key: "F#", is_major: false },
  { key: "G", is_major: false },
  { key: "G#", is_major: false },
  { key: "Ab", is_major: false },
  { key: "A", is_major: false },
  { key: "A#", is_major: false },
  { key: "Bb", is_major: false },
  { key: "B", is_major: false },
  { key: "C", is_major: false },
  { key: "C#", is_major: false },
  { key: "D", is_major: false },
  { key: "D#", is_major: false },
  // Major keys
  { key: "Eb", is_major: true },
  { key: "E", is_major: true },
  { key: "F", is_major: true },
  { key: "F#", is_major: true },
  { key: "Gb", is_major: true },
  { key: "G", is_major: true },
  { key: "Ab", is_major: true },
  { key: "A", is_major: true },
  { key: "Bb", is_major: true },
  { key: "B", is_major: true },
  { key: "C", is_major: true },
  { key: "C#", is_major: true },
  { key: "Db", is_major: true },
  { key: "D", is_major: true },
];
